### PR TITLE
install dependencies automatically, set up Travis CI

### PR DESCRIPTION
**Pull request by dongzhuoer**
Installing dependencies should be done automatically. It's cumbersome to ask user to install needed package one be one. Further more, it makes the package hard to maintain.

Continuous integration (I use Travis CI here) can help you detect bugs early and keep you confident when release a new version.

### CODE REVIEW

**Comment by dongzhuoer** [comment]
Sorry to disturb you for the two failed attempt: #4 #5.

It took me a **whole** day to make things work.

**Comment by dongzhuoer** [comment]
Travis CI only works on the forked repository now. To enable it in your repository, you need to finish the first two steps of [getting started guide](https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI) and then trigger a commit (simply push a new commit or manually via https://travis-ci.org/)

**Comment by ChenMengjie** [comment]
Thanks a lot. Does it work now?

________________________________

**Comment by dongzhuoer** [comment]
Yes. Congratulations!

**Comment by dongzhuoer** [comment]
By the way, do you have summer research internship (self-funded) position in your lab? I am a senior undergradute student in Nankai University, China. I have sent you an email from dongzhuoer.cn@outlook.com before.

**Pull request merged**
